In [32]:
import pandas as pd
import numpy as np
import seaborn as sns
import plotly.express as px
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler #Normalization
from sklearn.preprocessing import RobustScaler
from sklearn.preprocessing import MaxAbsScaler
from sklearn.model_selection import train_test_split

In [6]:
df=pd.read_csv("heart.csv")

In [8]:
df=pd.read_csv("heart.csv",usecols=['Age','RestingBP','Cholesterol','MaxHR',"HeartDisease"])

In [9]:
df

Age  RestingBP  Cholesterol  MaxHR  HeartDisease
0     40        140          289    172             0
1     49        160          180    156             1
2     37        130          283     98             0
3     48        138          214    108             1
4     54        150          195    122             0
..   ...        ...          ...    ...           ...
913   45        110          264    132             1
914   68        144          193    141             1
915   57        130          131    115             1
916   57        130          236    174             1
917   38        138          175    173             0

[918 rows x 5 columns]

In [14]:
Y=df['HeartDisease']
Y

0      0
1      1
2      0
3      1
4      0
      ..
913    1
914    1
915    1
916    1
917    0
Name: HeartDisease, Length: 918, dtype: int64

In [12]:
X=df.drop(['HeartDisease'],axis=1)
X

Age  RestingBP  Cholesterol  MaxHR
0     40        140          289    172
1     49        160          180    156
2     37        130          283     98
3     48        138          214    108
4     54        150          195    122
..   ...        ...          ...    ...
913   45        110          264    132
914   68        144          193    141
915   57        130          131    115
916   57        130          236    174
917   38        138          175    173

[918 rows x 4 columns]

In [15]:
X_train,X_test,y_train,y_test=train_test_split(X,Y,test_size=0.2,random_state=0)

In [17]:
X_train,X_test,y_train,y_test

(     Age  RestingBP  Cholesterol  MaxHR
 378   70        140            0    157
 356   46        115            0    113
 738   65        160          360    151
 85    66        140          139     94
 427   59        140            0    117
 ..   ...        ...          ...    ...
 835   54        110          239    126
 192   48        130          245    160
 629   57        128          303    159
 559   64        134          273    102
 684   47        108          243    152
 
 [734 rows x 4 columns],
      Age  RestingBP  Cholesterol  MaxHR
 306   55        115            0    155
 711   66        120          302    151
 298   51        110            0     92
 466   55        120            0    125
 253   62        140          271    152
 ..   ...        ...          ...    ...
 909   63        124          197    136
 293   65        115            0     93
 761   52        112          230    160
 2     37        130          283     98
 409   53        160          

In [19]:
sc= StandardScaler()
minmax= MinMaxScaler() #Normalization
rbs= RobustScaler()
maxab= MaxAbsScaler()

In [21]:
x_train_sc=sc.fit_transform(X_train)
x_test_sc=sc.transform(X_test)

In [28]:
x_train_minmax=minmax.fit_transform(X_train)
x_test_minmax=minmax.transform(X_test)

In [29]:
x_train_rbs=rbs.fit_transform(X_train)
x_tets_rbs=rbs.transform(X_test)

In [31]:
x_train_maxab=maxab.fit_transform(X_train)
x_test_rbs=rbs.transform(X_test)

In [34]:
x_train_maxab

array([[0.90909091, 0.7       , 0.        , 0.77722772],
       [0.5974026 , 0.575     , 0.        , 0.55940594],
       [0.84415584, 0.8       , 0.59701493, 0.74752475],
       ...,
       [0.74025974, 0.64      , 0.50248756, 0.78712871],
       [0.83116883, 0.67      , 0.45273632, 0.5049505 ],
       [0.61038961, 0.54      , 0.40298507, 0.75247525]])

In [35]:
x_train_rbs

array([[ 1.25490196,  0.5       , -2.4735376 ,  0.52777778],
       [-0.62745098, -0.75      , -2.4735376 , -0.69444444],
       [ 0.8627451 ,  1.5       ,  1.53760446,  0.36111111],
       ...,
       [ 0.23529412, -0.1       ,  0.90250696,  0.58333333],
       [ 0.78431373,  0.2       ,  0.56824513, -1.        ],
       [-0.54901961, -1.1       ,  0.23398329,  0.38888889]])

In [36]:
x_train_minmax

array([[0.85714286, 0.7       , 0.        , 0.67625899],
       [0.36734694, 0.575     , 0.        , 0.35971223],
       [0.75510204, 0.8       , 0.59701493, 0.63309353],
       ...,
       [0.59183673, 0.64      , 0.50248756, 0.69064748],
       [0.73469388, 0.67      , 0.45273632, 0.28057554],
       [0.3877551 , 0.54      , 0.40298507, 0.64028777]])

In [37]:
x_train_sc

array([[ 1.75354017,  0.40398537, -1.85006457,  0.79313997],
       [-0.81787111, -0.95050604, -1.85006457, -0.92450561],
       [ 1.21782949,  1.48757849,  1.49894114,  0.55891557],
       ...,
       [ 0.3606924 , -0.24617051,  0.9686819 ,  0.87121477],
       [ 1.11068735,  0.07890743,  0.6895981 , -1.353917  ],
       [-0.71072897, -1.32976364,  0.41051429,  0.59795297]])