In [73]:
import pandas as pd
import numpy as np
import seaborn as sns
from sklearn.preprocessing import OneHotEncoder #input non-order
from sklearn.preprocessing import LabelEncoder  #output label
from sklearn.preprocessing import OrdinalEncoder #input order
from sklearn.model_selection import train_test_split

In [6]:
df=pd.read_csv('customer.csv')

In [7]:
df

age  gender   review education purchased
0    30  Female  Average    School        No
1    68  Female     Poor        UG        No
2    70  Female     Good        PG        No
3    72  Female     Good        PG        No
4    16  Female  Average        UG        No
5    31  Female  Average    School       Yes
6    18    Male     Good    School        No
7    60  Female     Poor    School       Yes
8    65  Female  Average        UG        No
9    74    Male     Good        UG       Yes
10   98  Female     Good        UG       Yes
11   74    Male     Good        UG       Yes
12   51    Male     Poor    School        No
13   57  Female  Average    School        No
14   15    Male     Poor        PG       Yes
15   75    Male     Poor        UG        No
16   59    Male     Poor        UG       Yes
17   22  Female     Poor        UG       Yes
18   19    Male     Good    School        No
19   97    Male     Poor        PG       Yes
20   57  Female  Average    School       Yes
21   32    Male  Average        PG        No
22   18  Female     Poor        PG       Yes
23   96  Female     Good    School        No
24   16  Female  Average        PG       Yes
25   57  Female     Good    School        No
26   53  Female     Poor        PG        No
27   69  Female     Poor        PG        No
28   48    Male     Poor    School        No
29   83  Female  Average        UG       Yes
30   73    Male  Average        UG        No
31   22  Female     Poor    School       Yes
32   92    Male  Average        UG       Yes
33   89  Female     Good        PG       Yes
34   86    Male  Average    School        No
35   74    Male     Poor    School       Yes
36   34  Female     Good        UG       Yes
37   94    Male  Average        PG       Yes
38   45  Female     Good    School        No
39   76    Male     Poor        PG        No
40   39    Male     Good    School        No
41   23    Male     Good        PG       Yes
42   30  Female     Good        PG       Yes
43   27    Male     Poor        PG        No
44   77  Female  Average        UG        No
45   61    Male     Poor        PG       Yes
46   64  Female     Poor        PG        No
47   38  Female     Good        PG       Yes
48   39  Female     Good        UG       Yes
49   25  Female     Good        UG        No

In [60]:
X=df.drop(['purchased','age','gender'],axis=1)
Y=df['purchased']
X.sample(4),Y.sample(4)
X

review education
0   Average    School
1      Poor        UG
2      Good        PG
3      Good        PG
4   Average        UG
5   Average    School
6      Good    School
7      Poor    School
8   Average        UG
9      Good        UG
10     Good        UG
11     Good        UG
12     Poor    School
13  Average    School
14     Poor        PG
15     Poor        UG
16     Poor        UG
17     Poor        UG
18     Good    School
19     Poor        PG
20  Average    School
21  Average        PG
22     Poor        PG
23     Good    School
24  Average        PG
25     Good    School
26     Poor        PG
27     Poor        PG
28     Poor    School
29  Average        UG
30  Average        UG
31     Poor    School
32  Average        UG
33     Good        PG
34  Average    School
35     Poor    School
36     Good        UG
37  Average        PG
38     Good    School
39     Poor        PG
40     Good    School
41     Good        PG
42     Good        PG
43     Poor        PG
44  Average        UG
45     Poor        PG
46     Poor        PG
47     Good        PG
48     Good        UG
49     Good        UG

In [64]:
X_train,X_test,y_train,y_test=train_test_split(X,Y,test_size=0.2)

In [65]:
X_train

review education
22     Poor        PG
2      Good        PG
4   Average        UG
49     Good        UG
18     Good    School
1      Poor        UG
3      Good        PG
32  Average        UG
38     Good    School
46     Poor        PG
41     Good        PG
35     Poor    School
9      Good        UG
45     Poor        PG
27     Poor        PG
12     Poor    School
16     Poor        UG
13  Average    School
34  Average    School
11     Good        UG
17     Poor        UG
42     Good        PG
43     Poor        PG
37  Average        PG
5   Average    School
20  Average    School
26     Poor        PG
36     Good        UG
40     Good    School
44  Average        UG
30  Average        UG
31     Poor    School
28     Poor    School
24  Average        PG
33     Good        PG
48     Good        UG
6      Good    School
19     Poor        PG
39     Poor        PG
23     Good    School

In [66]:
le=LabelEncoder() #output_data

In [55]:
y_train_le=le.fit_transform(y_train)
y_test_le=le.transform(y_test)

In [56]:
y_train_le,y_test_le

(array([1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1,
        0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0]),
 array([0, 1, 1, 1, 0, 0, 0, 1, 1, 0]))

In [67]:
X_train

review education
22     Poor        PG
2      Good        PG
4   Average        UG
49     Good        UG
18     Good    School
1      Poor        UG
3      Good        PG
32  Average        UG
38     Good    School
46     Poor        PG
41     Good        PG
35     Poor    School
9      Good        UG
45     Poor        PG
27     Poor        PG
12     Poor    School
16     Poor        UG
13  Average    School
34  Average    School
11     Good        UG
17     Poor        UG
42     Good        PG
43     Poor        PG
37  Average        PG
5   Average    School
20  Average    School
26     Poor        PG
36     Good        UG
40     Good    School
44  Average        UG
30  Average        UG
31     Poor    School
28     Poor    School
24  Average        PG
33     Good        PG
48     Good        UG
6      Good    School
19     Poor        PG
39     Poor        PG
23     Good    School

In [71]:
oe=OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']]) #order data for input
# oe = OrdinalEncoder(categories=['Poor','Average','Good'])
# oe = OrdinalEncoder(categories=['Poor','Average','Good'])
oe.fit(X_train)
oe.transform(X_train)
oe.transform(X_test)

array([[0., 0.],
       [1., 1.],
       [2., 2.],
       [0., 1.],
       [1., 1.],
       [2., 0.],
       [0., 2.],
       [1., 0.],
       [1., 2.],
       [2., 1.]])

In [84]:
ohe=OneHotEncoder(sparse=False,dtype=np.int32)
ohe_X_train=ohe.fit_transform(X_train)

/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


In [85]:
ohe_X_train

array([[0, 0, 1, 1, 0, 0],
       [0, 1, 0, 1, 0, 0],
       [1, 0, 0, 0, 0, 1],
       [0, 1, 0, 0, 0, 1],
       [0, 1, 0, 0, 1, 0],
       [0, 0, 1, 0, 0, 1],
       [0, 1, 0, 1, 0, 0],
       [1, 0, 0, 0, 0, 1],
       [0, 1, 0, 0, 1, 0],
       [0, 0, 1, 1, 0, 0],
       [0, 1, 0, 1, 0, 0],
       [0, 0, 1, 0, 1, 0],
       [0, 1, 0, 0, 0, 1],
       [0, 0, 1, 1, 0, 0],
       [0, 0, 1, 1, 0, 0],
       [0, 0, 1, 0, 1, 0],
       [0, 0, 1, 0, 0, 1],
       [1, 0, 0, 0, 1, 0],
       [1, 0, 0, 0, 1, 0],
       [0, 1, 0, 0, 0, 1],
       [0, 0, 1, 0, 0, 1],
       [0, 1, 0, 1, 0, 0],
       [0, 0, 1, 1, 0, 0],
       [1, 0, 0, 1, 0, 0],
       [1, 0, 0, 0, 1, 0],
       [1, 0, 0, 0, 1, 0],
       [0, 0, 1, 1, 0, 0],
       [0, 1, 0, 0, 0, 1],
       [0, 1, 0, 0, 1, 0],
       [1, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 1],
       [0, 0, 1, 0, 1, 0],
       [0, 0, 1, 0, 1, 0],
       [1, 0, 0, 1, 0, 0],
       [0, 1, 0, 1, 0, 0],
       [0, 1, 0, 0, 0, 1],
       [0, 1, 0, 0, 1, 0],
 